# Generated by Django 5.0.2 on 2024-03-02 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_progroup_amount_to_pay_schedule_session_sessionuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progroup',
            name='amount_to_pay',
        ),
    ]
