# Generated by Django 5.0.2 on 2024-03-02 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_remove_progroup_amount_to_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionuser',
            name='assisted',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='sessionuser',
            name='late',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='sessionuser',
            name='paid',
            field=models.BooleanField(null=True),
        ),
    ]
