# Generated by Django 5.0.2 on 2024-03-02 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0004_alter_sessionuser_assisted_alter_sessionuser_late_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionuser',
            name='assisted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sessionuser',
            name='late',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sessionuser',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
