# Generated by Django 5.0.2 on 2024-03-02 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0005_alter_sessionuser_assisted_alter_sessionuser_late_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='num_players',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
