# Generated by Django 5.0.2 on 2024-03-02 05:10

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0006_session_num_players'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=250)),
                ('time', models.PositiveIntegerField(null=True)),
                ('sessions', models.PositiveIntegerField(null=True)),
                ('done', models.BooleanField(default=False)),
                ('progroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offenses', to='group.progroup')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
