# Generated by Django 5.0.2 on 2024-03-02 05:22

import datetime
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0007_offense'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offense',
            name='done',
        ),
        migrations.CreateModel(
            name='OffenseUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('date', models.DateTimeField(default=datetime.datetime(2024, 3, 2, 5, 22, 31, 390129, tzinfo=datetime.timezone.utc))),
                ('time', models.PositiveIntegerField(null=True)),
                ('sessions', models.PositiveIntegerField(null=True)),
                ('offense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offense_users', to='group.offense')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offense_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
