# Generated by Django 5.0.2 on 2024-03-02 05:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0008_remove_offense_done_offenseuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offenseuser',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
