# Generated by Django 5.0.2 on 2024-03-18 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0009_alter_offenseuser_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progroupuser',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member')], default='member', max_length=10),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
