# Generated by Django 5.0.2 on 2024-03-25 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0011_schedule_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='progroup',
            name='code',
            field=models.CharField(default='', max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='progroup',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
