# Generated by Django 5.0.2 on 2024-03-31 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0012_progroup_code_alter_progroup_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='num_players',
        ),
        migrations.AddField(
            model_name='schedule',
            name='number_of_players',
            field=models.PositiveBigIntegerField(default=18),
            preserve_default=False,
        ),
    ]
