# Generated by Django 5.0.2 on 2024-04-08 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0014_schedule_open_day_schedule_open_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='progroup',
        ),
        migrations.AddField(
            model_name='session',
            name='schedule',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='group.schedule'),
            preserve_default=False,
        ),
    ]
