# Generated by Django 5.0.2 on 2024-04-08 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0015_remove_session_progroup_session_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
